version: '3'
services:
  web:
    build: .
    command: npm run dev
    volumes:
        - .:/usr/app/
        - /usr/app/node_modules
    ports:
        - "8000:8000"
    depends_on: 
        - db
  db:
    ports: 
        - 5432:5432
    image: postgres
    restart: always
    environment:
        - POSTGRES_USER=pasin_be
        - POSTGRES_PASSWORD=pasin_be1337
        - POSTGRES_DB=pasin_be
    volumes:
        - database-data:/var/lib/postgresql/data/
volumes: 
  database-data: